version: '3.9'

services:   
  postgres:
    image: postgres
    # env_file:
    #   - .env
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: storefront_dev

    volumes:
      - './postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  web:
    build: .
    links:
      - postgres
    image: sql-express-storefront
    depends_on: 
      - postgres
    ports: 
      - "3000:3000"
    env_file:
      - .env

volumes:
  postgres:
