version: '3.9'

services:   
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
    # environment: 
      - .env
      # POSTGRES_HOST: localhost
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_USER: postgres
      # POSTGRES_DB: storefront_dev
    volumes:
      - './postgres:/var/lib/postgresql/data'

  web:
    build: .
    image: sql-express-storefront
    depends_on: 
      - postgres
    ports: 
      - '3000:3000'
    # env_file:
    #   - .env

volumes:
  postgres:
